routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/home', function () {
    return redirect( '/members/' . \Auth::user()->id );
});

Auth::routes();

Route::resource('members', 'MembersController');
Route::resource('subscription', 'SubscriptionController');
Route::resource('transactions', 'TransactionController');
Route::resource('legislature', 'RegulationsController');

Route::get('about/organisation', function () {
    return redirect('about');
});

Route::get('about', 'PagesController@about');
Route::post('contact', 'PagesController@sendmail');
Route::post('find', 'MembersController@search');
Route::post('search', 'PagesController@search');

// If the route does not exist but the view does display the view
Route::get('{view}', function($view){
    if(file_exists(config('view.paths')[0] . "/$view.blade.php"))
        return view(str_replace('/', '.', $view));
    else
        abort(404);
});

Route::get('{parent}/{view}', function($parent, $view){
    if(file_exists(config('view.paths')[0] . "/$parent/$view.blade.php"))
        return view("$parent.$view");
    else
        abort(404);
});

app/Member.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\UploadedFile;

class Member extends User
{
    protected $table = 'users';

    /**
     * Update a member's profile information
     *
     * @param integer $id
     * @param MemberUpdateRequest $request
     * @return void
     */
    public static function muto(int $id, MemberUpdateRequest $request)
    {
        $member = Member::find($id);
        $data = $request->all();
        if( $request->hasFile( 'image' ) )
            $data['image'] = Member::upload_image( $request->image );
        $member->update( $data );
        $member->save();
        return $member;
    }

    /**
     * Find members in a specific city
     *
     * @param string $city
     * @return object
     */
    public static function by_city( string $city )
    {
        $members = Member::where( 'city', $city )->get();
        return $members;
    }

    /**
     * Find members in a specific specialty
     *
     * @param string $specialty
     * @return object
     */
    public static function by_specialty( string $specialty )
    {
        $members = Member::where( 'specialty', $specialty )->get();
        return $members;
    }

    /**
     * Upload an image and return its path
     *
     * @param UploadedFile $image
     * @return string
     */
    public static function upload_image( UploadedFile $image )
    {
        return 'storage/' . $image->store( 'uploads', 'public' );
    }


    public static function search( string $string )
    {
        return Member::where( 'name', 'like', "%$string%" )
                    ->orWhere( 'bio', 'like', "%$string%" )
                    ->orWhere( 'specialty', 'like', "%$string%" )
                    ->orWhere( 'city', 'like', "%$string%" )
                    ->get();
    }
}

app/Http/Controllers/MembersController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\MemberUpdateRequest;
use App\Http\Requests\MemberSearchRequest;
use App\Member;
use App\Subscription;

class MembersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('members.index', ['members' => Member::all()]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return redirect('register');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        dd($request);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data = Member::find($id);
        $data->same_city = Member::by_city( $data->city );
        $data->same_specialty = Member::by_specialty( $data->specialty );
        $data->subs_current = Subscription::current($id);
        return view('members.show', $data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = Member::find($id);
        return view('members.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update( MemberUpdateRequest $request, $id)
    {
        Member::muto( $id, $request );
        return redirect('members/'.$id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        return "Are you sure you want to do this?";
    }

    public function search( MemberSearchRequest $r )
    {
        $members = Member::search( $r->string );
        if ( $r->ajax() )
            return $members;
        return view('members.index', ['members' => $members]);
    }
}

resources/views/members/edit.blade.php
@extends('layouts.app')
@section('page_title', 'Edit '.$name)
@section('head_scripts')
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.5.1/dist/leaflet.css" integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ==" crossorigin=""/>
    <script src="https://unpkg.com/leaflet@1.5.1/dist/leaflet.js" integrity="sha512-GffPMF3RvMeYyc1LWMHtK8EbPv0iNZ8/oTtHPx9/cc2ILxQ+u905qIwdpULaqDkyBKgOaB57QTMg7ztg8Jm2Og==" crossorigin=""></script>
    <script src="{{ asset('js/Control.Coordinates.js') }}"></script>
    <link rel="stylesheet" href="{{ asset('js/Control.Coordinates.js') }}">
    <style>
        #map { 
            position:relative; 
            height:300px; 
            width:100% 
        }
        
        .leaflet-control-coordinates {
            background: white;
            border-radius: 4px;
            box-shadow: 0 1px 5px rgba(0, 0, 0, 0.65);
            cursor: pointer;
            padding: 2px 5px;
        }

        .leaflet-control-coordinates.hidden {
            display: none;
        }

        .leaflet-control-coordinates-lng {
            padding-left: 5px;
        }
    </style>
@endsection

@section('content')
<section class="ulockd-about-one">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-sm-12 col-md-8 col-md-offset-2">
                <div class="">

                    <div class="">
                        <form class="general-form" method="POST" action="{{ route('members.update', $id) }}" enctype="multipart/form-data">
                            @csrf
                            {{ method_field('PATCH') }}
                                
                            <div class="form-group row">
                                <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>

                                <div class="col-md-6">
                                    <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ old('name') ? old('name') : $name }}" required autocomplete="name" autofocus>

                                    @error('name')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="username" class="col-md-4 col-form-label text-md-right">{{ __('Username') }}</label>

                                <div class="col-md-6">
                                    <input id="username" type="username" class="form-control @error('username') is-invalid @enderror" name="username" value="{{ old('username') ? old('username') : $username  }}" required autocomplete="username">

                                    @error('username')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="email" class="col-md-4 col-form-label text-md-right">E-Mail Address</label>

                                <div class="col-md-6">
                                    <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ old('email') ? old('email') : $email  }}" required autocomplete="email">

                                    @error('email')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            
                            <div class="form-group row">
                                <label for="mobile_number" class="col-md-4 col-form-label text-md-right">Mobile Number <span class='form-hint'>Will not be shown to the public</span></label>

                                <div class="col-md-6">
                                    <input id="mobile_number" type="text" class="form-control @error('mobile_number') is-invalid @enderror" name="mobile_number" value="{{ old('mobile_number') ? old('mobile_number') : $mobile_number }}" autocomplete="phone">

                                    @error('mobile_number')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            
                            <div class="form-group row">
                                <label for="phone" class="col-md-4 col-form-label text-md-right">Business Phone</label>

                                <div class="col-md-6">
                                    <input id="phone" type="text" class="form-control @error('phone') is-invalid @enderror" name="phone" value="{{ old('phone') ? old('phone') : $phone }}" autocomplete="phone">

                                    @error('phone')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            
                            <div class="form-group row">
                                <label for="contact_email" class="col-md-4 col-form-label text-md-right">Contact Email</label>

                                <div class="col-md-6">
                                    <input id="contact_email" type="text" class="form-control @error('contact_email') is-invalid @enderror" name="contact_email" value="{{ old('contact_email') ? old('contact_email') : $contact_email }}" autocomplete="email">

                                    @error('contact_email')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            
                            <div class="form-group row">
                                <label for="bio" class="col-md-4 col-form-label text-md-right">About the practice <span class="form-hint">Feel free to use HTML tags</span></label>

                                <div class="col-md-6">
                                    <textarea id="bio" name="bio" class="form-control ulockd-form-tb" rows="8" placeholder="About the practice" data-error="Message is required.">{{ old('bio') ? old('bio') : $bio }}</textarea>    
                                    @error('bio')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            
                            <div class="form-group row">
                                <label for="address" class="col-md-4 col-form-label text-md-right">Physical Address</label>

                                <div class="col-md-6">
                                    <input id="address" type="text" class="form-control @error('address') is-invalid @enderror" name="address" value="{{ old('address') ? old('address') : $address }}" autocomplete="address">

                                    @error('address')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            
                            <div class="form-group row">
                                <label for="city" class="col-md-4 col-form-label text-md-right">City / Town</label>

                                <div class="col-md-6">
                                    <input id="city" type="text" class="form-control @error('city') is-invalid @enderror" name="city" value="{{ old('city') ? old('city') : $city }}" autocomplete="city">

                                    @error('city')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            
                            <div class="form-group row">
                                <label for="latlong" class="col-md-4 col-form-label text-md-right">Location <span class="form-hint">Use map below to pick your location</span></label>

                                <div class="col-md-6">
                                    <input id="latlong" type="text" class="form-control @error('latlong') is-invalid @enderror" name="latlong" value="{{ old('latlong') ? old('latlong') : $latlong }}">

                                    @error('latlong')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <div id="map"></div>
                            </div>
                            
                            <div class="form-group row">
                                <label for="image" class="col-md-4 col-form-label text-md-right">Profile image <span class="form-hint">Max size 1MB. Please resize before uploadin</span></label>

                                <div class="col-md-6">
                                    <input id="image" type="file" class="form-control @error('image') is-invalid @enderror" name="image" >

                                    @error('image')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row mb-0">
                                <div class="col-md-6 offset-md-4">
                                    <button type="submit" class="btn ulockd-btn-green">
                                        Update Profile
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

@endsection

@section('footer_scripts')
    <script>
		var map = L.map('map').setView([{{ $latlong }}], 8);

		L.tileLayer('http://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}.png', {
			maxZoom: 18,
			attribution: '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors, &copy; <a href="https://carto.com/attributions">CARTO</a>'
		}).addTo(map);

		var c = new L.Control.Coordinates();
		//c.addTo(map);

        var marker = L.marker([{{ $latlong }}]).addTo(map);

		function onMapClick(e) {
			if (marker) { // check
                map.removeLayer(marker); // remove
            }
            marker = new L.Marker(e.latlng).addTo(map); // set
            $('#latlong').val(e.latlng.lat.toFixed(6) + ', ' + e.latlng.lng.toFixed(6));
		}

		map.on('click', onMapClick);
    </script>
@endsection

resources/views/members/index.blade.php
@extends('layouts.app')
@section('page_title', 'Members')
@section('content')

	<!-- Our Shop -->
	<section class="ulockd-search-results">
		<div class="container">
			<div class="row">
				<div class="col-lg-9">
					<div class="row ulockd-mrgn1260 ulockd-shop-menubar ulockd-mrgn635">
						<div class="col-lg-7">
							<ul class="list-inline">
								<li><span class="flaticon-person text-thm2"></span></li>
								<li><p>Showing {{ count($members) }} results</p></li>
							</ul>
						</div>
						<div class="col-lg-5">
							<form action="{{ url( 'find' ) }}" method="post">
						    <div class="input-group ulockd-product-searchbar">
						        <input type="text" class="form-control" name="string" placeholder="Search members">
										@csrf
						        <span class="input-group-btn">
						        	<button class="btn btn-default" type="submit">Search</button>
						        </span>
						    </div><!-- /input-group -->
							</form>
						</div><!-- /.col-lg-6 -->
					</div>
					<div class="row ulockd-mrgn1260">
                    @foreach( $members as $member )
                        <div class="row search-results-row">
                            <div class="col-md-4 col-xl-4 offset-xl-0">
                                <img class="img-responsive" src="{{ asset($member->image?$member->image:'uploads/nopic.png') }}" />
                            </div>
                            <div class="col-md-4 col-xl-7">
                                <h3><a href="{{ url('member/'.$member->id) }}">{{ $member->name }}</a></h3>
                                <p class="small-grey-italics">{{ $member->qualifications }}</p>
                                <p>Specialty: {{ $member->specialty }}</p>
                                <p>URL: <a href="{{ $member->website }}" target="_blank">Visit Website</a></p>
                                <a href="{{ url('members/'.$member->id) }}" class="btn btn-lg ulockd-btn-green hvr-bounce-to-right">View Profile</a>
                            </div>
                            <div class="col-md-4 col-xl-7">
                                <div class="top-right-label">
                                   {{ $member->city }}
                                </div>
                            </div>
                        </div>
                    @endforeach                        
					</div>
				</div>
				<div class="col-lg-3">
					<div class="ulockd-all-service ulockd-mrgn1260">
						<div class="ulockd-tag-list-title">
							<h3 class="ulockd-bb-dashed"><span class="flaticon-mark text-thm1"></span> Browse by City</h3>
						</div>
						<div class="list-group">
						    <a href="#" class="list-group-item">All of Zimbabwe</a>
						    <a href="#" class="list-group-item">Harare</a>
						    <a href="#" class="list-group-item">Bulawayo</a>
						    <a href="#" class="list-group-item">Gweru</a>
						    <a href="#" class="list-group-item">Mutare</a>
						    <a href="#" class="list-group-item">Victoria Falls</a>
						    <a href="#" class="list-group-item">Kariba</a>
						    <a href="#" class="list-group-item">Kadoma</a>
						</div>
					</div>
					<div class="ulockd-ip-tag">
						<div class="ulockd-tag-list-title">
							<h3 class="ulockd-bb-dashed"><span class="flaticon-mark text-thm1"></span> Search by Specialty</h3>
						</div>
						<ul class="list-inline ulockd-tag-list-details">
							<li><a href="#">Small Animals</a></li>
							<li><a href="#">Cats</a></li>
							<li><a href="#">Horses</a></li>
							<li><a href="#">Cattle</a></li>
							<li><a href="#">Other</a></li>
						</ul>
					</div>
				</div>
				<!-- 
				<div class="col-lg-12">
					<nav class="ulockd-shop-pagination" aria-label="Page navigation">
					  <ul class="pagination">
					    <li>
					      <a href="#" aria-label="Previous">
					        <span aria-hidden="true">&laquo;</span>
					      </a>
					    </li>
					    <li><a href="#">1</a></li>
					    <li><a href="#">2</a></li>
					    <li><a href="#">3</a></li>
					    <li><a href="#">4</a></li>
					    <li><a href="#">5</a></li>
					    <li>
					      <a href="#" aria-label="Next">
					        <span aria-hidden="true">&raquo;</span>
					      </a>
					    </li>
					  </ul>
					</nav>
				</div>
				 -->
			</div>
		</div>
	</section>
@endsection

resources/views/members/show.blade.php
@extends('layouts.app')

@section('page_title', $name )

@section('head_scripts')
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.5.1/dist/leaflet.css" integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ==" crossorigin=""/>
    <script src="https://unpkg.com/leaflet@1.5.1/dist/leaflet.js" integrity="sha512-GffPMF3RvMeYyc1LWMHtK8EbPv0iNZ8/oTtHPx9/cc2ILxQ+u905qIwdpULaqDkyBKgOaB57QTMg7ztg8Jm2Og==" crossorigin=""></script>
    <style>
        #map { height:300px }
    </style>
@endsection

@section('content')
	<!-- Member Profile -->
	<section class="ulockd-shop">
		<div class="container">
			<div class="row">
				<div class="col-lg-9">
					<div class="row ulockd-mrgn1260">
						<div class="col-sm-6 col-md-6 col-lg-5 clearfix">
							<div class="ulockd-member-details-img">
                                <img class="img-responsive img-whp" src="{{ asset( $image ? $image:'uploads/nopic.png'  ) }}" alt="{{ $name }}">
                                
							</div>
						</div>
						<div class="col-sm-6 col-md-6 col-lg-7 clearfix">
							<div class="ulockd-member-details">
								<h2 class="price">{{ $name }} </h2>
                                <p class="small-grey-italics">{{ $qualifications }}</p>
                                
                                <p><strong>Specialisation: </strong>{{ $specialty }}</p>
                                <p><strong>Phone: </strong>{{ $phone }}</p>
                                <p><strong>Email: </strong>{{ $contact_email }}</p>
                                <p><strong><a href="{{ $website }}" class="member-site-url">Visit Website</a></strong></p>
                                <p><strong>Address: </strong>{{ $address }}</p>
                                <p><strong>City/Town: </strong>{{ $city }}</p>
								<a class="btn btn-lg ulockd-btn-green hvr-bounce-to-right" href="#">Contact member</a>
								@if ( can_edit( $id ) )
								<a class="btn btn-lg ulockd-btn-green hvr-bounce-to-right" href="{{ url('members/'.$id.'/edit') }}">Edit Profile</a>
								@endif
							</div>
						</div>
						<div class="col-lg-12 ulockd-mrgn1260">
							<div class="ulockd-member-details">
								<h2 class="price">About </h2>
                                {!! $bio !!}
							</div>
							<div class="ulockd-member-details">
								<h2 class="price">Location </h2>
								<div id="map"></div>
							</div>
						</div>
					</div>
				</div>
				<div class="col-lg-3 ulockd-pad-zero">
					@if( sizeof($same_city) > 1 )
					<h3 class="ulockd-bb-dashed"><span class="flaticon-calendar text-thm1"></span> Also from {{ $city }}</h3>
					<div class="list-group">
							@foreach( $same_city as $scp )
								@if( $scp->id != $id )
								<a href="{{ url( 'members/' . $scp->id ) }}" class="list-group-item">
								{{ $scp->name }}
								<span class="sidebar-list-small-details">{{ $scp->address }}</span>
								</a>
								@endif
							@endforeach
					</div>
					@endif

					@if( sizeof($same_specialty) > 1 )
					<h3 class="ulockd-bb-dashed"><span class="flaticon-calendar text-thm1"></span> Also specialising in<br>{{ $specialty }}</h3>
					<div class="list-group">
							@foreach( $same_specialty as $ssp )
								@if( $ssp->id != $id )
								<a href="{{ url( 'members/' . $ssp->id ) }}" class="list-group-item">
								{{ $ssp->name }}
								<span class="sidebar-list-small-details">{{ $ssp->address }}</span>
								</a>
								@endif
							@endforeach
					</div>
					@endif
				</div>
			</div>
		</div>
	</section>
@endsection

@section('footer_scripts')
    <script>
        var map = L.map('map').setView([{{ $latlong }}], 13);
        L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accessToken}', {
            attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors, <a href="https://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
            maxZoom: 18,
            id: 'mapbox.streets',
            accessToken: 'pk.eyJ1Ijoicm9nZ2llIiwiYSI6ImNqeDZ4ZjU2dDA0NnozeWp5a3Zvdml1eDcifQ.uXPWg0VPZw_CEbba60AQgA'
        }).addTo(map);
        var marker = L.marker([{{ $latlong }}]).addTo(map);
        marker.bindPopup("<b>{{ $name }}</b><br>{{ $address }}").openPopup();
    </script>
@endsection